export const CLEAR_ALL_CAT_DATA = 'CLEAR_ALL_CAT_DATA';
export const CLEAR_CAT_LIST = 'CLEAR_CAT_LIST';
export const CLEAR_SELECTED_CAT = 'CLEAR_SELECTED_CAT';
export const CLEAR_SELECTED_KIND = 'CLEAR_SELECTED_KIND';
export const CLEAR_SELECTED_CHARC = 'CLEAR_SELECTED_CHARC';
export const CLEAR_CAT_TYPE_LIST = 'CLEAR_CAT_TYPE_LIST';

export const FETCH_CAT_LIST = 'FETCH_CAT_LIST';
export const FETCH_CAT_TYPE_LIST = 'FETCH_CAT_TYPE_LIST';
export const FETCH_SELECTED_CAT = 'FETCH_SELECTED_CAT';
export const FETCH_SELECTED_KIND = 'FETCH_SELECTED_KIND';
export const FETCH_SELECTED_CHARC = 'FETCH_SELECTED_CHARC';

export const FETCH_LAST_KEYWORD = 'FETCH_LAST_KEYWORD';
export const FETCH_CUR_PAGE = 'FETCH_CUR_PAGE';
export const FETCH_IS_END_DATA = 'FETCH_IS_END_DATA';

export const CLEAR_FOCUS_DATE = 'CLEAR_FOCUS_DATE';
export const CLEAR_TODO_LIST = 'CLEAR_TODO_LIST';
export const FETCH_FOCUS_DATE = 'FETCH_FOCUS_DATE';
export const FETCH_TODO_LIST = 'FETCH_TODO_LIST';
export const FETCH_CUR_STATUS = 'FETCH_CUR_STATUS';

export const FETCH_EDIT_FLAG = 'FETCH_EDIT_FLAG';